### ISSUE TITLE
can this be adjusted for api logins?

### ISSUE THREAD

**Issue by ikzelf** [buxxi/mod_auth_form-sample#1]
Hi,
this already looks very nice so I put a web app behind this page. The web app has an api url and when apps try to connect, the get the login form, what they do not expect because they already send their credentials in the request. This works with pure Basic Auth but not with this form.
Is this something that can be easily fixed?
I can imagine that the java script could detect that the request already had the credentials in them ....

```
        answer = requests.post(self.server + "/", data=data_api, proxies=self.proxies, verify=self.verify,
                               auth=requests.auth.HTTPBasicAuth(self.basic_auth_user, self.basic_auth_pass))
        cookie = answer.cookies
```

the cookie is created by the application but this point is not reached.

**Comment by buxxi** [comment]
Hi,

I mostly made this as a documentation for a note to myself the next time I need to setup a server and password protect something more than something ready to use.

With that said I don't think anything could be done in javascript since it's client side if it's an app trying to connect to an api.

but if you can set a cookie mod_auth_form seems to have this kind of format (just plain text):
``
session=<AuthName>-user=<username-field>&<AuthName>-pw=<password-field>;path=/
``
where ``<AuthName>`` should be replaced with the value that was specified in the configuration (authenticationform in my example).
